name: Zephyr Build & Test

on:
  pull_request:
    branches:
      - main  # Adjust this to your default branch

jobs:
  build_and_test:
    runs-on: self-hosted  # Ensure your runner has this label
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 1
          
      - name: Debug Paths
        run: |
          echo "Listing ~/workspace:"
          ls -la ~/workspace
          echo "Listing ~/workspace/zephyr:"
          ls -la ~/workspace/zephyr
          echo "Listing ~/workspace/modules:"
          ls -la ~/workspace/modules

      - name: Run Zephyr Docker Build
        run: |
          docker run --rm -v ${{ github.workspace }}:/work -v ~/workspace/zephyr:/work/zephyr -v ~/workspace/modules:/work/modules -w /work mmpzephyr:latest \
            west build -b stm32_min_dev@blue -s .

      - name: Flash and Run Tests
        run: |
          docker run --rm --privileged -v /dev/serial:/dev/serial -v ${{ github.workspace }}:/work -w /work mmpzephyr \
            west flash

