name: Zephyr Build & Test

on:
  pull_request:
    branches:
      - main  # Adjust this to your default branch

jobs:
  build_and_test:
    runs-on: self-hosted  # Ensure your runner has this label
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 1
          
      - name: Debug Paths
        run: |
          echo "Listing ~/workspace:"
          ls -la ~/workspace

      - name: Docker Paths
        run: |
          docker run --rm -v ${{ github.workspace }}:/workdir -v ~/workspace/zephyr:/workdir/zephyr -v ~/workspace/modules:/workdir/modules -w /workdir mmpzephyr:latest \
            ls -la /workdir

      - name: Run Zephyr Docker Build
        run: |
          docker run --rm -v ${{ github.workspace }}:/workdir -v ~/workspace/zephyr:/workdir/zephyr -v ~/workspace/modules:/workdir/modules -w /workdir mmpzephyr:latest \
            west build -b stm32_min_dev@blue -s example-application/app -p

      - name: Flash and Run Tests
        run: |
          docker run --rm --privileged -v /dev/serial:/dev/serial -v ${{ github.workspace }}:/workdir -v ~/workspace/zephyr:/workdir/zephyr -v ~/workspace/modules:/workdir/modules -w /workdir mmpzephyr \
            west flash

